POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "user@user.com",
  "password": "123456"
}

###
GET http://localhost:3000/test-auth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoidXNlckB1c2VyLmNvbSIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTcwNjY3ODk0NSwiZXhwIjoxNzA2Njc5MDA1fQ.5qdsMVSdaFACdG7kbLRH2pePHFfsmovV2kkf9tNos8Q